FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /MasarykBOT

RUN apt-get update && \
    apt-get install -y git build-essential && \
    apt-get install -y --no-install-recommends dvipng texlive-latex-extra texlive-fonts-recommended cm-super

COPY bot/requirements.txt bot/requirements.txt
RUN pip install -r bot/requirements.txt

RUN mkdir -p logs/ && touch logs/bot.log

ENTRYPOINT ["python"]
CMD ["-m", "bot"]
