FROM python:3.8.2-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /MasarykBOT
COPY . /MasarykBOT

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

CMD ["python", "./__main__.py"]
